Repository mipt-npm/kmath, pull requests merged in 2021-04, with the labels that each got.

#270 Remove redundant try-catch expressions
  kmath-ast/src/commonMain/kotlin/space/kscience/kmath/ast/MST.kt
  kmath-ast/src/jsMain/kotlin/space/kscience/kmath/estree/estree.kt
  kmath-ast/src/jvmMain/kotlin/space/kscience/kmath/asm/asm.kt
Labels: misc

#268 Add pi and e constants, some unrelated changes
  examples/src/main/kotlin/space/kscience/kmath/structures/StreamDoubleFieldND.kt
  kmath-ast/src/commonMain/kotlin/space/kscience/kmath/ast/MstAlgebra.kt
  kmath-ast/src/commonMain/kotlin/space/kscience/kmath/ast/rendering/LatexSyntaxRenderer.kt
  kmath-ast/src/commonMain/kotlin/space/kscience/kmath/ast/rendering/MathMLSyntaxRenderer.kt
  kmath-ast/src/commonMain/kotlin/space/kscience/kmath/ast/rendering/MathRenderer.kt
  kmath-ast/src/commonMain/kotlin/space/kscience/kmath/ast/rendering/MathSyntax.kt
  kmath-ast/src/commonMain/kotlin/space/kscience/kmath/ast/rendering/features.kt
  kmath-ast/src/jvmTest/kotlin/space/kscience/kmath/ast/rendering/TestFeatures.kt
  kmath-ast/src/jvmTest/kotlin/space/kscience/kmath/ast/rendering/TestLatex.kt
  kmath-ast/src/jvmTest/kotlin/space/kscience/kmath/ast/rendering/TestMathML.kt
  kmath-commons/src/main/kotlin/space/kscience/kmath/commons/expressions/DerivativeStructureExpression.kt
  kmath-complex/src/commonMain/kotlin/space/kscience/kmath/complex/Complex.kt
  kmath-complex/src/commonMain/kotlin/space/kscience/kmath/complex/ComplexFieldND.kt
  kmath-core/api/kmath-core.api
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/expressions/FunctionalExpressionAlgebra.kt
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/expressions/SimpleAutoDiff.kt
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/nd/AlgebraND.kt
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/nd/DoubleFieldND.kt
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/operations/Algebra.kt
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/operations/AlgebraElements.kt
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/operations/NumericAlgebra.kt
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/operations/numbers.kt
  kmath-stat/src/jvmTest/kotlin/space/kscience/kmath/stat/StatisticTest.kt
  kmath-viktor/api/kmath-viktor.api
  kmath-viktor/src/main/kotlin/space/kscience/kmath/viktor/ViktorStructureND.kt
Labels: feature

#281 Tests for large BigIntegers multiplication and power are provided.
  benchmarks/src/jvmMain/kotlin/space/kscience/kmath/benchmarks/BigIntBenchmark.kt
Labels: performance

#283 Update dependencies
  kmath-ast/build.gradle.kts
  kmath-ast/src/commonMain/kotlin/space/kscience/kmath/ast/parser.kt
Labels: misc

#289 Move AST rendering tests to common
  kmath-ast/src/commonTest/kotlin/space/kscisnce/kmath/ast/rendering/TestFeatures.kt
  kmath-ast/src/commonTest/kotlin/space/kscisnce/kmath/ast/rendering/TestLatex.kt
  kmath-ast/src/commonTest/kotlin/space/kscisnce/kmath/ast/rendering/TestMathML.kt
  kmath-ast/src/commonTest/kotlin/space/kscisnce/kmath/ast/rendering/TestStages.kt
  kmath-ast/src/commonTest/kotlin/space/kscisnce/kmath/ast/rendering/TestUtils.kt
Labels: test

#274 Redesign exponential function rendering
  kmath-ast/src/commonMain/kotlin/space/kscience/kmath/ast/rendering/LatexSyntaxRenderer.kt
  kmath-ast/src/commonMain/kotlin/space/kscience/kmath/ast/rendering/MathMLSyntaxRenderer.kt
  kmath-ast/src/commonMain/kotlin/space/kscience/kmath/ast/rendering/MathRenderer.kt
  kmath-ast/src/commonMain/kotlin/space/kscience/kmath/ast/rendering/MathSyntax.kt
  kmath-ast/src/commonMain/kotlin/space/kscience/kmath/ast/rendering/features.kt
  kmath-ast/src/commonMain/kotlin/space/kscience/kmath/ast/rendering/multiplatformToString.kt
  kmath-ast/src/commonMain/kotlin/space/kscience/kmath/ast/rendering/stages.kt
  kmath-ast/src/commonTest/kotlin/space/kscience/kmath/ast/ParserPrecedenceTest.kt
  kmath-ast/src/commonTest/kotlin/space/kscience/kmath/ast/ParserTest.kt
  kmath-ast/src/commonTest/kotlin/space/kscience/kmath/ast/rendering/TestFeatures.kt
  kmath-ast/src/commonTest/kotlin/space/kscience/kmath/ast/rendering/TestLatex.kt
  kmath-ast/src/commonTest/kotlin/space/kscience/kmath/ast/rendering/TestMathML.kt
  kmath-ast/src/commonTest/kotlin/space/kscience/kmath/ast/rendering/TestStages.kt
  kmath-ast/src/commonTest/kotlin/space/kscience/kmath/ast/rendering/TestUtils.kt
  kmath-ast/src/jsMain/kotlin/space/kscience/kmath/ast/rendering/multiplatformToString.kt
  kmath-ast/src/jvmMain/kotlin/space/kscience/kmath/ast/rendering/multiplatformToString.kt
Labels: feature

#291 Update README.md
  kmath-ast/README.md
  kmath-ast/docs/README-TEMPLATE.md
Labels: documentation

#301 Use GraalVM as CI JDK
  .github/workflows/build.yml
  .github/workflows/pages.yml
  .github/workflows/publish.yml
Labels: misc
