Repository mipt-npm/kmath, pull requests merged in 2021-11, with the labels that each got.

#436 Multiple performance improvements related to ASM
  benchmarks/build.gradle.kts
  benchmarks/src/jvmMain/kotlin/space/kscience/kmath/benchmarks/ExpressionsInterpretersBenchmark.kt
  buildSrc/src/main/kotlin/space/kscience/kmath/benchmarks/addBenchmarkProperties.kt
  examples/build.gradle.kts
  examples/src/main/kotlin/space/kscience/kmath/ast/expressions.kt
  kmath-ast/src/jvmMain/kotlin/space/kscience/kmath/asm/asm.kt
  kmath-ast/src/jvmMain/kotlin/space/kscience/kmath/asm/internal/AsmBuilder.kt
  kmath-core/build.gradle.kts
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/expressions/Expression.kt
Labels: performance

#437 Provide specializations of `AsmBuilder` for `Double`, `Long`, `Int`
  README.md
  benchmarks/src/jvmMain/kotlin/space/kscience/kmath/benchmarks/ExpressionsInterpretersBenchmark.kt
  examples/src/main/kotlin/space/kscience/kmath/ast/expressions.kt
  kmath-ast/README.md
  kmath-ast/build.gradle.kts
  kmath-ast/src/commonTest/kotlin/space/kscience/kmath/ast/TestCompilerOperations.kt
  kmath-ast/src/jsMain/kotlin/space/kscience/kmath/wasm/internal/WasmBuilder.kt
  kmath-ast/src/jsMain/kotlin/space/kscience/kmath/wasm/wasm.kt
  kmath-ast/src/jvmMain/kotlin/space/kscience/kmath/asm/asm.kt
  kmath-ast/src/jvmMain/kotlin/space/kscience/kmath/asm/internal/AsmBuilder.kt
  kmath-ast/src/jvmMain/kotlin/space/kscience/kmath/asm/internal/ByteArrayClassLoader.kt
  kmath-ast/src/jvmMain/kotlin/space/kscience/kmath/asm/internal/GenericAsmBuilder.kt
  kmath-ast/src/jvmMain/kotlin/space/kscience/kmath/asm/internal/PrimitiveAsmBuilder.kt
  kmath-ast/src/jvmMain/kotlin/space/kscience/kmath/asm/internal/mapIntrinsics.kt
  kmath-ast/src/jvmTest/kotlin/space/kscience/kmath/ast/utils.kt
  kmath-complex/README.md
  kmath-core/README.md
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/expressions/Symbol.kt
  kmath-ejml/README.md
  kmath-for-real/README.md
  kmath-functions/README.md
  kmath-jafama/README.md
  kmath-kotlingrad/README.md
  kmath-nd4j/README.md
  kmath-tensors/README.md
Labels: performance

#435 Feat/permsort
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/misc/sorting.kt
  kmath-core/src/commonTest/kotlin/space/kscience/kmath/misc/PermSortTest.kt
Labels: feature

#443 Update gradle-tools, make Kotlin 1.6.0 migrations
  benchmarks/build.gradle.kts
  build.gradle.kts
  buildSrc/build.gradle.kts
  examples/build.gradle.kts
  kmath-ast/build.gradle.kts
  kmath-commons/src/main/kotlin/space/kscience/kmath/commons/random/CMRandomGeneratorWrapper.kt
  kmath-core/build.gradle.kts
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/misc/annotations.kt
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/operations/BufferAlgebra.kt
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/operations/DoubleBufferField.kt
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/operations/DoubleBufferOps.kt
  kmath-coroutines/build.gradle.kts
  kmath-jafama/build.gradle.kts
  kmath-jupyter/build.gradle.kts
  kmath-optimization/build.gradle.kts
  kmath-tensors/build.gradle.kts
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/core/DoubleTensorAlgebra.kt
  settings.gradle.kts
Labels: misc
