Repository mipt-npm/kmath, pull requests merged in 2021-06, with the labels that each got.

#359 Enable build workflow for external PRs (w/manual approval)
  .github/workflows/build.yml
Labels: misc

#363 Fix README.md again
  README.md
  docs/templates/README-TEMPLATE.md
  kmath-ast/README.md
  kmath-complex/README.md
  kmath-core/README.md
  kmath-ejml/README.md
  kmath-for-real/README.md
  kmath-functions/README.md
  kmath-kotlingrad/README.md
  kmath-nd4j/README.md
  kmath-tensors/README.md
Labels: documentation

#360 Add justCalculate benchmark to inspect overhead of Expression API, some minor refactorings
  benchmarks/src/jvmMain/kotlin/space/kscience/kmath/benchmarks/ExpressionsInterpretersBenchmark.kt
  examples/src/main/kotlin/space/kscience/kmath/ast/expressions.kt
  kmath-ast/README.md
  kmath-ast/docs/README-TEMPLATE.md
  kmath-ast/src/commonTest/kotlin/space/kscience/kmath/ast/TestCompilerConsistencyWithInterpreter.kt
  kmath-ast/src/commonTest/kotlin/space/kscience/kmath/ast/TestCompilerOperations.kt
  kmath-ast/src/commonTest/kotlin/space/kscience/kmath/ast/TestCompilerVariables.kt
  kmath-ast/src/jsMain/kotlin/space/kscience/kmath/wasm/internal/WasmBuilder.kt
  kmath-ast/src/jsTest/kotlin/space/kscience/kmath/ast/TestExecutionTime.kt
  kmath-ast/src/jsTest/kotlin/space/kscience/kmath/wasm/TestWasmSpecific.kt
  kmath-ast/src/jvmMain/kotlin/space/kscience/kmath/asm/internal/codegenUtils.kt
  kmath-kotlingrad/src/test/kotlin/space/kscience/kmath/kotlingrad/AdaptingTests.kt
Labels: misc, performance

#357 integrate: Jafama + KMath
  README.md
  benchmarks/build.gradle.kts
  benchmarks/src/jvmMain/kotlin/space/kscience/kmath/benchmarks/JafamaBenchmark.kt
  examples/build.gradle.kts
  examples/src/main/kotlin/space/kscience/kmath/jafama/KMathaJafamaDemo.kt
  kmath-jafama/README.md
  kmath-jafama/build.gradle.kts
  kmath-jafama/src/main/kotlin/space/kscience/kmath/jafama/KMathJafama.kt
  settings.gradle.kts
Labels: feature, performance

#369 Generated benchmarking reports
  benchmarks/build.gradle.kts
  benchmarks/src/jvmMain/kotlin/space/kscience/kmath/benchmarks/JafamaBenchmark.kt
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/space/kscience/kmath/benchmarks/JmhReport.kt
  buildSrc/src/main/kotlin/space/kscience/kmath/benchmarks/addBenchmarkProperties.kt
  kmath-ast/build.gradle.kts
  kmath-jafama/README.md
  kmath-jafama/docs/README-TEMPLATE.md
  settings.gradle.kts
Labels: documentation

#370 Some refactoring of AST rendering
  kmath-ast/src/commonMain/kotlin/space/kscience/kmath/ast/rendering/MathRenderer.kt
  kmath-ast/src/commonMain/kotlin/space/kscience/kmath/ast/rendering/features.kt
  kmath-ast/src/commonMain/kotlin/space/kscience/kmath/ast/rendering/phases.kt
Labels: misc

#371 Refactor benchmark report writer
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/space/kscience/kmath/benchmarks/addBenchmarkProperties.kt
  settings.gradle.kts
Labels: misc

#372 Update CMRandomGeneratorWrapper
  kmath-commons/src/main/kotlin/space/kscience/kmath/commons/random/CMRandomGeneratorWrapper.kt
Labels: misc
