Repository mipt-npm/kmath, pull requests merged in 2021-08, with the labels that each got.

#395 Extend CI timeout and update GraalVM
  .github/workflows/build.yml
  .github/workflows/pages.yml
  .github/workflows/publish.yml
Labels: misc

#394 Add `contentEquals` extension to ND algebra and `LinearSpace`
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/linear/LinearSpace.kt
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/nd/StructureND.kt
Labels: feature

#399 Avoid using `kapt` in `kmath-jupyter`
  kmath-jupyter/build.gradle.kts
  settings.gradle.kts
Labels: misc

#406 Fix copyright in `ejmlCodegen.kt`
  buildSrc/src/main/kotlin/space/kscience/kmath/ejml/codegen/ejmlCodegen.kt
Labels: bug

#403 Ignore `TestExecutionTime` suite to reduce build time
  kmath-ast/src/jsTest/kotlin/space/kscience/kmath/ast/TestExecutionTime.kt
Labels: misc

#124 Initial geometry projections implemetations
  kmath-geometry/src/commonMain/kotlin/space/kscience/kmath/geometry/Euclidean2DSpace.kt
  kmath-geometry/src/commonMain/kotlin/space/kscience/kmath/geometry/Euclidean3DSpace.kt
  kmath-geometry/src/commonMain/kotlin/space/kscience/kmath/geometry/Projections.kt
  kmath-geometry/src/commonTest/kotlin/space/kscience/kmath/geometry/Euclidean2DSpaceTest.kt
  kmath-geometry/src/commonTest/kotlin/space/kscience/kmath/geometry/Euclidean3DSpaceTest.kt
  kmath-geometry/src/commonTest/kotlin/space/kscience/kmath/geometry/ProjectionAlongTest.kt
  kmath-geometry/src/commonTest/kotlin/space/kscience/kmath/geometry/ProjectionOntoLineTest.kt
  kmath-geometry/src/commonTest/kotlin/space/kscience/kmath/geometry/Vector2DTest.kt
  kmath-geometry/src/commonTest/kotlin/space/kscience/kmath/geometry/Vector3DTest.kt
  kmath-geometry/src/commonTest/kotlin/space/kscience/kmath/geometry/testUtils.kt
Labels: feature

#407 Avoid using `kapt` in kmath-jupyter
  kmath-jupyter/src/main/kotlin/space/kscience/kmath/jupyter/KMathJupyter.kt
Labels: bug

#409 Fix #408
  kmath-stat/src/commonMain/kotlin/space/kscience/kmath/samplers/ZigguratNormalizedGaussianSampler.kt
Labels: bug

#412 Add debug property for dumping classes generated with ASM
  kmath-ast/src/jvmMain/kotlin/space/kscience/kmath/asm/internal/AsmBuilder.kt
Labels: misc
