Repository mipt-npm/kmath, pull requests merged in 2021-05, with the labels that each got.

#307 refactor
  examples/src/main/kotlin/space/kscience/kmath/tensors/OLSWithSVD.kt
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/core/algebras/DoubleLinearOpsTensorAlgebra.kt
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/core/algebras/DoubleTensorAlgebra.kt
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/core/broadcastUtils.kt
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/core/utils.kt
  kmath-tensors/src/commonTest/kotlin/space/kscience/kmath/tensors/core/TestDoubleLinearOpsAlgebra.kt
Labels: misc

#308 refactor
  examples/src/main/kotlin/space/kscience/kmath/tensors/LinearSystemSolvingWithLUP.kt
  examples/src/main/kotlin/space/kscience/kmath/tensors/OLSWithSVD.kt
  kmath-tensors/build.gradle.kts
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/core/BufferedTensor.kt
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/core/checks.kt
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/core/linUtils.kt
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/core/utils.kt
Labels: misc

#309 Simplify and revise test cases for MST compilation engines
  kmath-ast/src/commonTest/kotlin/space/kscience/kmath/ast/TestCompilerConsistencyWithInterpreter.kt
  kmath-ast/src/commonTest/kotlin/space/kscience/kmath/ast/TestCompilerOperations.kt
  kmath-ast/src/commonTest/kotlin/space/kscience/kmath/ast/TestCompilerVariables.kt
  kmath-ast/src/commonTest/kotlin/space/kscience/kmath/ast/TestParser.kt
  kmath-ast/src/commonTest/kotlin/space/kscience/kmath/ast/TestParserPrecedence.kt
  kmath-ast/src/commonTest/kotlin/space/kscience/kmath/ast/utils.kt
  kmath-ast/src/jsTest/kotlin/space/kscience/kmath/ast/utils.kt
  kmath-ast/src/jsTest/kotlin/space/kscience/kmath/estree/TestESTreeConsistencyWithInterpreter.kt
  kmath-ast/src/jsTest/kotlin/space/kscience/kmath/estree/TestESTreeOperationsSupport.kt
  kmath-ast/src/jsTest/kotlin/space/kscience/kmath/estree/TestESTreeSpecialization.kt
  kmath-ast/src/jsTest/kotlin/space/kscience/kmath/estree/TestESTreeVariables.kt
  kmath-ast/src/jsTest/kotlin/space/kscience/kmath/wasm/TestWasmOperationsSupport.kt
  kmath-ast/src/jsTest/kotlin/space/kscience/kmath/wasm/TestWasmSpecialization.kt
  kmath-ast/src/jvmTest/kotlin/space/kscience/kmath/asm/TestAsmConsistencyWithInterpreter.kt
  kmath-ast/src/jvmTest/kotlin/space/kscience/kmath/asm/TestAsmOperationsSupport.kt
  kmath-ast/src/jvmTest/kotlin/space/kscience/kmath/asm/TestAsmSpecialization.kt
  kmath-ast/src/jvmTest/kotlin/space/kscience/kmath/asm/TestAsmVariables.kt
  kmath-ast/src/jvmTest/kotlin/space/kscience/kmath/ast/utils.kt
Labels: test

#273 Add Jupyter integration
  CHANGELOG.md
  build.gradle.kts
  kmath-ast/src/commonMain/kotlin/space/kscience/kmath/ast/rendering/MathMLSyntaxRenderer.kt
  kmath-core/api/kmath-core.api
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/expressions/MstAlgebra.kt
  kmath-jupyter/build.gradle.kts
  kmath-jupyter/src/main/kotlin/space/kscience/kmath/jupyter/KMathJupyter.kt
  settings.gradle.kts
Labels: feature

#312 statistic algebra
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/api/StatisticTensorAlgebra.kt
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/core/algebras/DoubleStatisticTensorAlgebra.kt
Labels: feature

#311 MST rendering: support infix division, use arcsin instead sin^-1 form for inverse trigonometric functions
  README.md
  kmath-ast/README.md
  kmath-ast/docs/README-TEMPLATE.md
  kmath-ast/src/commonMain/kotlin/space/kscience/kmath/ast/rendering/LatexSyntaxRenderer.kt
  kmath-ast/src/commonMain/kotlin/space/kscience/kmath/ast/rendering/MathMLSyntaxRenderer.kt
  kmath-ast/src/commonMain/kotlin/space/kscience/kmath/ast/rendering/MathRenderer.kt
  kmath-ast/src/commonMain/kotlin/space/kscience/kmath/ast/rendering/MathSyntax.kt
  kmath-ast/src/commonMain/kotlin/space/kscience/kmath/ast/rendering/features.kt
  kmath-ast/src/commonMain/kotlin/space/kscience/kmath/ast/rendering/stages.kt
  kmath-ast/src/commonTest/kotlin/space/kscience/kmath/ast/rendering/TestFeatures.kt
  kmath-ast/src/commonTest/kotlin/space/kscience/kmath/ast/rendering/TestStages.kt
  kmath-for-real/README.md
  kmath-functions/README.md
Labels: feature

#300 KMP library for tensors
  README.md
  examples/build.gradle.kts
  examples/src/main/kotlin/space/kscience/kmath/tensors/DataSetNormalization.kt
  examples/src/main/kotlin/space/kscience/kmath/tensors/LinearSystemSolvingWithLUP.kt
  examples/src/main/kotlin/space/kscience/kmath/tensors/NeuralNetwork.kt
  examples/src/main/kotlin/space/kscience/kmath/tensors/OLSWithSVD.kt
  examples/src/main/kotlin/space/kscience/kmath/tensors/PCA.kt
  kmath-core/api/kmath-core.api
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/linear/LinearSpace.kt
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/nd/BufferND.kt
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/nd/Structure1D.kt
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/nd/Structure2D.kt
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/nd/StructureND.kt
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/structures/Buffer.kt
  kmath-tensors/README.md
  kmath-tensors/build.gradle.kts
  kmath-tensors/docs/README-TEMPLATE.md
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/api/AnalyticTensorAlgebra.kt
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/api/LinearOpsTensorAlgebra.kt
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/api/Tensor.kt
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/api/TensorAlgebra.kt
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/api/TensorPartialDivisionAlgebra.kt
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/core/BroadcastDoubleTensorAlgebra.kt
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/core/BufferedTensor.kt
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/core/DoubleTensor.kt
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/core/DoubleTensorAlgebra.kt
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/core/IntTensor.kt
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/core/internal/TensorLinearStructure.kt
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/core/internal/broadcastUtils.kt
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/core/internal/checks.kt
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/core/internal/linUtils.kt
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/core/internal/tensorCastsUtils.kt
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/core/internal/utils.kt
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/core/tensorCasts.kt
  kmath-tensors/src/commonTest/kotlin/space/kscience/kmath/tensors/core/TestBroadcasting.kt
  kmath-tensors/src/commonTest/kotlin/space/kscience/kmath/tensors/core/TestDoubleAnalyticTensorAlgebra.kt
  kmath-tensors/src/commonTest/kotlin/space/kscience/kmath/tensors/core/TestDoubleLinearOpsAlgebra.kt
  kmath-tensors/src/commonTest/kotlin/space/kscience/kmath/tensors/core/TestDoubleTensor.kt
  kmath-tensors/src/commonTest/kotlin/space/kscience/kmath/tensors/core/TestDoubleTensorAlgebra.kt
  settings.gradle.kts
Labels: feature

#326 Promote kmath-kotlingrad to experimental alongside minor documentation and API changes
  CHANGELOG.md
  README.md
  kmath-kotlingrad/README.md
  kmath-kotlingrad/build.gradle.kts
  kmath-kotlingrad/docs/README-TEMPLATE.md
  kmath-kotlingrad/src/main/kotlin/space/kscience/kmath/kotlingrad/DifferentiableMstExpression.kt
  kmath-kotlingrad/src/main/kotlin/space/kscience/kmath/kotlingrad/KMathNumber.kt
  kmath-kotlingrad/src/main/kotlin/space/kscience/kmath/kotlingrad/ScalarsAdapters.kt
  kmath-kotlingrad/src/test/kotlin/space/kscience/kmath/kotlingrad/AdaptingTests.kt
Labels: misc

#331 Special rendering of Quaternion
  kmath-complex/src/commonMain/kotlin/space/kscience/kmath/complex/Complex.kt
  kmath-jupyter/src/main/kotlin/space/kscience/kmath/jupyter/KMathJupyter.kt
Labels: feature

#337 Link to Kotlingrad documentation
  build.gradle.kts
Labels: documentation

#339 Code generation of EJML linear spaces
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/space/kscience/kmath/ejml/codegen/ejmlCodegen.kt
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/linear/MatrixFeatures.kt
  kmath-ejml/build.gradle.kts
  kmath-ejml/src/main/kotlin/space/kscience/kmath/ejml/EjmlLinearSpace.kt
  kmath-ejml/src/main/kotlin/space/kscience/kmath/ejml/EjmlMatrix.kt
  kmath-ejml/src/main/kotlin/space/kscience/kmath/ejml/EjmlVector.kt
  kmath-ejml/src/main/kotlin/space/kscience/kmath/ejml/_generated.kt
  kmath-ejml/src/test/kotlin/space/kscience/kmath/ejml/EjmlVectorTest.kt
Labels: feature

#343 Hard code specific imports in codegen
  buildSrc/src/main/kotlin/space/kscience/kmath/ejml/codegen/ejmlCodegen.kt
Labels: bug

#346 Add out variance to StructureND and its implementations where possible, make some unrelated changes
  CHANGELOG.md
  README.md
  docs/templates/README-TEMPLATE.md
  examples/src/main/kotlin/space/kscience/kmath/tensors/PCA.kt
  kmath-ast/README.md
  kmath-complex/README.md
  kmath-core/README.md
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/linear/MatrixBuilder.kt
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/linear/MatrixWrapper.kt
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/linear/VirtualMatrix.kt
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/nd/AlgebraND.kt
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/nd/BufferAlgebraND.kt
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/nd/BufferND.kt
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/nd/Structure1D.kt
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/nd/Structure2D.kt
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/nd/StructureND.kt
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/structures/Buffer.kt
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/structures/FlaggedBuffer.kt
  kmath-core/src/commonTest/kotlin/space/kscience/kmath/expressions/SimpleAutoDiffTest.kt
  kmath-coroutines/src/jvmMain/kotlin/space/kscience/kmath/structures/LazyStructureND.kt
  kmath-ejml/README.md
  kmath-ejml/src/main/kotlin/space/kscience/kmath/ejml/EjmlMatrix.kt
  kmath-for-real/README.md
  kmath-functions/README.md
  kmath-kotlingrad/README.md
  kmath-memory/build.gradle.kts
  kmath-nd4j/README.md
  kmath-tensors/README.md
Labels: feature, misc

#332 Nd4j based TensorAlgebra implementation
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/nd/AlgebraND.kt
  kmath-nd4j/build.gradle.kts
  kmath-nd4j/src/main/kotlin/space/kscience/kmath/nd4j/Nd4jArrayAlgebra.kt
  kmath-nd4j/src/main/kotlin/space/kscience/kmath/nd4j/Nd4jArrayIterator.kt
  kmath-nd4j/src/main/kotlin/space/kscience/kmath/nd4j/Nd4jArrayStructure.kt
  kmath-nd4j/src/main/kotlin/space/kscience/kmath/nd4j/Nd4jTensorAlgebra.kt
  kmath-nd4j/src/main/kotlin/space/kscience/kmath/nd4j/arrays.kt
  kmath-nd4j/src/test/kotlin/space/kscience/kmath/nd4j/Nd4jArrayAlgebraTest.kt
  kmath-nd4j/src/test/kotlin/space/kscience/kmath/nd4j/Nd4jArrayStructureTest.kt
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/api/TensorAlgebra.kt
  kmath-tensors/src/commonMain/kotlin/space/kscience/kmath/tensors/core/DoubleTensorAlgebra.kt
Labels: feature

#350 Rename `DifferentiableMstExpression`, fix #349
  CHANGELOG.md
  build.gradle.kts
  kmath-kotlingrad/build.gradle.kts
  kmath-kotlingrad/src/main/kotlin/space/kscience/kmath/kotlingrad/KotlingradExpression.kt
  kmath-kotlingrad/src/main/kotlin/space/kscience/kmath/kotlingrad/scalarsAdapters.kt
  kmath-nd4j/build.gradle.kts
Labels: bug, misc

#352 Fix unresolved reference in generated type parameter
  kmath-ast/src/jvmMain/kotlin/space/kscience/kmath/asm/internal/AsmBuilder.kt
  kmath-core/src/commonMain/kotlin/space/kscience/kmath/expressions/Symbol.kt
Labels: bug

#356 Fix up Symja build issues
  build.gradle.kts
  gradle.properties
  kmath-symja/build.gradle.kts
  kmath-symja/src/main/kotlin/space/kscience/kmath/symja/SymjaExpression.kt
Labels: misc
